require("core.packer_config.colorscheme")
require("core.packer_config.nvim_tree")
require("core.packer_config.lualine")
require("core.packer_config.telescope")
require("core.packer_config.treesitter")
require("core.packer_config.cmp")
require("core.packer_config.autopairs")
require("core.packer_config.comment")
require("core.packer_config.gitsigns")
require("core.packer_config.bufferline")
require("core.packer_config.toggleterm")
require("core.packer_config.cursorline")

require("core.packer_config.lsp")
